version: 2.1
jobs:
  build:
    working_directory: ~/public
    docker:
      - image: circleci/node:13.3.0
    steps:
      - checkout
      run:
        name: update-npm
        command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum: "package.json"}}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum: "package.json"}}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - store-artifacts:
          path: test-results.xml
          prefix: tests
      - store-artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml